import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

// Vedere quali varianti usaremo
const outfit = Outfit({ 
  weight: ['400', '700'],
  subsets: ["latin"],
  variable: '--font-outfit',
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>{children}</body>
    </html>
  );
}
